name = "ThreadsBasics"
uuid = "67456a42-1dca-4109-a031-0a68de7e3ad5"
authors = ["Mason Protter <mason.protter@icloud.com>"]
version = "0.2.0"

[deps]
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
StableTasks = "91464d47-22a1-43fe-8b7f-2d57ee82463f"

[compat]
ChunkSplitters = "2.1"
StableTasks = "0.1.2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
